// Additional Action & Comedy Movie Quotes (150+ quotes)
let additionalQuotes: [Quote] = [
    // Action Movies - 80s/90s
    Quote(id: 200, text: "Get to the chopper!", movie: "Predator", year: 1987),
    Quote(id: 201, text: "If it bleeds, we can kill it.", movie: "Predator", year: 1987),
    Quote(id: 202, text: "I ain't got time to bleed.", movie: "Predator", year: 1987),
    Quote(id: 203, text: "Come out to the coast, we'll get together, have a few laughs.", movie: "Die Hard", year: 1988),
    Quote(id: 204, text: "Now I have a machine gun. Ho-ho-ho.", movie: "Die Hard", year: 1988),
    Quote(id: 205, text: "I'm your worst nightmare.", movie: "Rambo: First Blood Part II", year: 1985),
    Quote(id: 206, text: "I could have killed 'em all, I could've killed you. In town you're the law, out here it's me.", movie: "First Blood", year: 1982),
    Quote(id: 207, text: "I'm too old for this shit.", movie: "Lethal Weapon", year: 1987),
    Quote(id: 208, text: "Diplomatic immunity!", movie: "Lethal Weapon 2", year: 1989),
    Quote(id: 209, text: "It's been revoked.", movie: "Lethal Weapon 2", year: 1989),
    Quote(id: 210, text: "I'm getting too old for this shit.", movie: "Lethal Weapon 2", year: 1989),
    Quote(id: 211, text: "Deserve's got nothin' to do with it.", movie: "Unforgiven", year: 1992),
    Quote(id: 212, text: "Go ahead, make my day.", movie: "Sudden Impact", year: 1983),
    Quote(id: 213, text: "Do you feel lucky, punk?", movie: "Dirty Harry", year: 1971),
    Quote(id: 214, text: "I know what you're thinking. 'Did he fire six shots or only five?'", movie: "Dirty Harry", year: 1971),
    Quote(id: 215, text: "Yippee-ki-yay, Mr. Falcon!", movie: "Die Hard 2", year: 1990),
    Quote(id: 216, text: "Just when I thought I was out, they pull me back in.", movie: "The Godfather Part III", year: 1990),
    Quote(id: 217, text: "I'm gonna take you to the bank, Senator Trent. To the blood bank.", movie: "Hard to Kill", year: 1990),
    Quote(id: 218, text: "Pain don't hurt.", movie: "Road House", year: 1989),
    Quote(id: 219, text: "I have come here to chew bubblegum and kick ass... and I'm all out of bubblegum.", movie: "They Live", year: 1988),
    Quote(id: 220, text: "Stick around.", movie: "Predator", year: 1987),
    
    // Comedies - 80s
    Quote(id: 221, text: "So I got that goin' for me, which is nice.", movie: "Caddyshack", year: 1980),
    Quote(id: 222, text: "Be the ball.", movie: "Caddyshack", year: 1980),
    Quote(id: 223, text: "Cinderella story. Outta nowhere.", movie: "Caddyshack", year: 1980),
    Quote(id: 224, text: "We're gonna need a bigger boat.", movie: "Jaws", year: 1975),
    Quote(id: 225, text: "Does Barry Manilow know that you raid his wardrobe?", movie: "The Breakfast Club", year: 1985),
    Quote(id: 226, text: "Don't you forget about me.", movie: "The Breakfast Club", year: 1985),
    Quote(id: 227, text: "Bueller?... Bueller?... Bueller?", movie: "Ferris Bueller's Day Off", year: 1986),
    Quote(id: 228, text: "Save Ferris.", movie: "Ferris Bueller's Day Off", year: 1986),
    Quote(id: 229, text: "Pardon my French, but you're an asshole!", movie: "Ferris Bueller's Day Off", year: 1986),
    Quote(id: 230, text: "I'm a god. I'm not THE God... I don't think.", movie: "Groundhog Day", year: 1993),
    Quote(id: 231, text: "Don't drive angry!", movie: "Groundhog Day", year: 1993),
    Quote(id: 232, text: "Bing!", movie: "Groundhog Day", year: 1993),
    Quote(id: 233, text: "We're on a mission from God.", movie: "The Blues Brothers", year: 1980),
    Quote(id: 234, text: "It's 106 miles to Chicago, we got a full tank of gas, half a pack of cigarettes, it's dark, and we're wearing sunglasses.", movie: "The Blues Brothers", year: 1980),
    Quote(id: 235, text: "Hit it.", movie: "The Blues Brothers", year: 1980),
    Quote(id: 236, text: "Human sacrifice, dogs and cats living together... mass hysteria!", movie: "Ghostbusters", year: 1984),
    Quote(id: 237, text: "Back off, man. I'm a scientist.", movie: "Ghostbusters", year: 1984),
    Quote(id: 238, text: "Yes, it's true. This man has no dick.", movie: "Ghostbusters", year: 1984),
    Quote(id: 239, text: "Ray, when someone asks you if you're a god, you say YES!", movie: "Ghostbusters", year: 1984),
    Quote(id: 240, text: "We got one!", movie: "Ghostbusters", year: 1984),
    
    // Comedies - 90s
    Quote(id: 241, text: "That's what I love about these high school girls, man. I get older, they stay the same age.", movie: "Dazed and Confused", year: 1993),
    Quote(id: 242, text: "Alright, alright, alright.", movie: "Dazed and Confused", year: 1993),
    Quote(id: 243, text: "Party at the moon tower!", movie: "Dazed and Confused", year: 1993),
    Quote(id: 244, text: "I'm funny how? Funny like a clown? I amuse you?", movie: "Goodfellas", year: 1990),
    Quote(id: 245, text: "Never rat on your friends and always keep your mouth shut.", movie: "Goodfellas", year: 1990),
    Quote(id: 246, text: "What's in the box?!", movie: "Se7en", year: 1995),
    Quote(id: 247, text: "Ernest Hemingway once wrote, 'The world is a fine place and worth fighting for.' I agree with the second part.", movie: "Se7en", year: 1995),
    Quote(id: 248, text: "Big Gulps, huh? Alright! Well, see ya later!", movie: "Dumb and Dumber", year: 1994),
    Quote(id: 249, text: "Just when I think you couldn't possibly be any dumber, you go and do something like this... and totally redeem yourself!", movie: "Dumb and Dumber", year: 1994),
    Quote(id: 250, text: "Mock! Yeah! Ing! Yeah! Bird! Yeah! Yeah! Yeah!", movie: "Dumb and Dumber", year: 1994),
    Quote(id: 251, text: "Samsonite! I was way off!", movie: "Dumb and Dumber", year: 1994),
    Quote(id: 252, text: "What if he shot me in the face?", movie: "Dumb and Dumber", year: 1994),
    Quote(id: 253, text: "I'm gonna hang by the bar. Put out the vibe.", movie: "Swingers", year: 1996),
    Quote(id: 254, text: "You're so money and you don't even know it!", movie: "Swingers", year: 1996),
    Quote(id: 255, text: "Vegas, baby! Vegas!", movie: "Swingers", year: 1996),
    Quote(id: 256, text: "I'm not even supposed to be here today!", movie: "Clerks", year: 1994),
    Quote(id: 257, text: "37! My girlfriend sucked 37 dicks!", movie: "Clerks", year: 1994),
    Quote(id: 258, text: "In a row?", movie: "Clerks", year: 1994),
    Quote(id: 259, text: "Snootchie bootchies!", movie: "Jay and Silent Bob Strike Back", year: 2001),
    Quote(id: 260, text: "I am Jack's complete lack of surprise.", movie: "Fight Club", year: 1999),
    Quote(id: 261, text: "His name is Robert Paulson.", movie: "Fight Club", year: 1999),
    Quote(id: 262, text: "I want you to hit me as hard as you can.", movie: "Fight Club", year: 1999),
    Quote(id: 263, text: "This is your life and it's ending one minute at a time.", movie: "Fight Club", year: 1999),
    Quote(id: 264, text: "We buy things we don't need with money we don't have to impress people we don't like.", movie: "Fight Club", year: 1999),
    
    // More Action
    Quote(id: 265, text: "I'm not locked in here with you. You're locked in here with me!", movie: "Watchmen", year: 2009),
    Quote(id: 266, text: "Are you not entertained?!", movie: "Gladiator", year: 2000),
    Quote(id: 267, text: "What we do in life echoes in eternity.", movie: "Gladiator", year: 2000),
    Quote(id: 268, text: "My name is Maximus Decimus Meridius.", movie: "Gladiator", year: 2000),
    Quote(id: 269, text: "Gentlemen, you can't fight in here! This is the War Room!", movie: "Dr. Strangelove", year: 1964),
    Quote(id: 270, text: "I love the smell of napalm in the morning.", movie: "Apocalypse Now", year: 1979),
    Quote(id: 271, text: "The horror... the horror...", movie: "Apocalypse Now", year: 1979),
    Quote(id: 272, text: "Charlie don't surf!", movie: "Apocalypse Now", year: 1979),
    Quote(id: 273, text: "Game over, man! Game over!", movie: "Aliens", year: 1986),
    Quote(id: 274, text: "Get away from her, you bitch!", movie: "Aliens", year: 1986),
    Quote(id: 275, text: "They mostly come at night... mostly.", movie: "Aliens", year: 1986),
    Quote(id: 276, text: "In space, no one can hear you scream.", movie: "Alien", year: 1979),
    Quote(id: 277, text: "I have a bad feeling about this.", movie: "Star Wars", year: 1977),
    Quote(id: 278, text: "Do. Or do not. There is no try.", movie: "The Empire Strikes Back", year: 1980),
    Quote(id: 279, text: "Never tell me the odds!", movie: "The Empire Strikes Back", year: 1980),
    Quote(id: 280, text: "It's a trap!", movie: "Return of the Jedi", year: 1983),
    
    // More Comedies
    Quote(id: 281, text: "I'm in a glass case of emotion!", movie: "Anchorman", year: 2004),
    Quote(id: 282, text: "60% of the time, it works every time.", movie: "Anchorman", year: 2004),
    Quote(id: 283, text: "I love lamp.", movie: "Anchorman", year: 2004),
    Quote(id: 284, text: "Milk was a bad choice!", movie: "Anchorman", year: 2004),
    Quote(id: 285, text: "That escalated quickly.", movie: "Anchorman", year: 2004),
    Quote(id: 286, text: "I'm kind of a big deal.", movie: "Anchorman", year: 2004),
    Quote(id: 287, text: "Stay classy, San Diego.", movie: "Anchorman", year: 2004),
    Quote(id: 288, text: "You're my boy, Blue!", movie: "Old School", year: 2003),
    Quote(id: 289, text: "We're going streaking!", movie: "Old School", year: 2003),
    Quote(id: 290, text: "Earmuffs!", movie: "Old School", year: 2003),
    Quote(id: 291, text: "That's how you get ants!", movie: "Archer", year: 2009),
    Quote(id: 292, text: "I'm not superstitious, but I am a little stitious.", movie: "The Office", year: 2005),
    Quote(id: 293, text: "That's what she said.", movie: "The Office", year: 2005),
    Quote(id: 294, text: "Bears. Beets. Battlestar Galactica.", movie: "The Office", year: 2005),
    Quote(id: 295, text: "I declare bankruptcy!", movie: "The Office", year: 2005),
    Quote(id: 296, text: "I'm not a hero. I'm a high-functioning sociopath.", movie: "Sherlock", year: 2010),
    Quote(id: 297, text: "Elementary.", movie: "Sherlock", year: 2010),
    Quote(id: 298, text: "I'm having an old friend for dinner.", movie: "The Silence of the Lambs", year: 1991),
    Quote(id: 299, text: "A census taker once tried to test me.", movie: "The Silence of the Lambs", year: 1991),
    Quote(id: 300, text: "It puts the lotion on its skin.", movie: "The Silence of the Lambs", year: 1991),
    
    // Classic Action & Adventure
    Quote(id: 301, text: "Snakes. Why'd it have to be snakes?", movie: "Raiders of the Lost Ark", year: 1981),
    Quote(id: 302, text: "It belongs in a museum!", movie: "Indiana Jones and the Last Crusade", year: 1989),
    Quote(id: 303, text: "You chose... poorly.", movie: "Indiana Jones and the Last Crusade", year: 1989),
    Quote(id: 304, text: "No ticket.", movie: "Indiana Jones and the Last Crusade", year: 1989),
    Quote(id: 305, text: "We named the dog Indiana.", movie: "Indiana Jones and the Last Crusade", year: 1989),
    Quote(id: 306, text: "Kali Ma!", movie: "Indiana Jones and the Temple of Doom", year: 1984),
    Quote(id: 307, text: "Fortune and glory, kid. Fortune and glory.", movie: "Indiana Jones and the Temple of Doom", year: 1984),
    Quote(id: 308, text: "I'm your huckleberry.", movie: "Tombstone", year: 1993),
    Quote(id: 309, text: "You tell 'em I'm coming... and hell's coming with me!", movie: "Tombstone", year: 1993),
    Quote(id: 310, text: "Why Johnny Ringo, you look like somebody just walked over your grave.", movie: "Tombstone", year: 1993),
    Quote(id: 311, text: "I got two guns, one for each of ya.", movie: "Tombstone", year: 1993),
    Quote(id: 312, text: "Skin that smoke wagon and see what happens!", movie: "Tombstone", year: 1993),
    Quote(id: 313, text: "I'm your Huckleberry.", movie: "Tombstone", year: 1993),
    Quote(id: 314, text: "Say when.", movie: "Tombstone", year: 1993),
    Quote(id: 315, text: "Wyatt Earp is my friend.", movie: "Tombstone", year: 1993),
    
    // More 90s Comedies
    Quote(id: 316, text: "Schwing!", movie: "Wayne's World", year: 1992),
    Quote(id: 317, text: "We're not worthy!", movie: "Wayne's World", year: 1992),
    Quote(id: 318, text: "Party on, Wayne!", movie: "Wayne's World", year: 1992),
    Quote(id: 319, text: "Excellent!", movie: "Wayne's World", year: 1992),
    Quote(id: 320, text: "If you build it, he will come.", movie: "Field of Dreams", year: 1989),
    Quote(id: 321, text: "Is this heaven? No, it's Iowa.", movie: "Field of Dreams", year: 1989),
    Quote(id: 322, text: "Go the distance.", movie: "Field of Dreams", year: 1989),
    Quote(id: 323, text: "Surely you can't be serious. I am serious... and don't call me Shirley.", movie: "Airplane!", year: 1980),
    Quote(id: 324, text: "I picked the wrong week to quit smoking.", movie: "Airplane!", year: 1980),
    Quote(id: 325, text: "Looks like I picked the wrong week to quit drinking.", movie: "Airplane!", year: 1980),
    Quote(id: 326, text: "Have you ever seen a grown man naked?", movie: "Airplane!", year: 1980),
    Quote(id: 327, text: "Joey, do you like movies about gladiators?", movie: "Airplane!", year: 1980),
    Quote(id: 328, text: "The white zone is for loading and unloading only.", movie: "Airplane!", year: 1980),
    Quote(id: 329, text: "There's a sale at Penney's!", movie: "Airplane!", year: 1980),
    Quote(id: 330, text: "I am serious. And don't call me Shirley.", movie: "Airplane!", year: 1980),
    
    // Cult Classics
    Quote(id: 331, text: "Obviously you're not a golfer.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 332, text: "This is what happens when you fuck a stranger in the ass!", movie: "The Big Lebowski", year: 1998),
    Quote(id: 333, text: "Shut the fuck up, Donny!", movie: "The Big Lebowski", year: 1998),
    Quote(id: 334, text: "You're out of your element!", movie: "The Big Lebowski", year: 1998),
    Quote(id: 335, text: "That's just, like, your opinion, man.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 336, text: "I'm the Dude. So that's what you call me.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 337, text: "Yeah, well, that's just like your opinion, man.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 338, text: "This is a very complicated case, Maude. You know, a lotta ins, lotta outs.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 339, text: "Nice marmot.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 340, text: "The Dude abides. I don't know about you but I take comfort in that.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 341, text: "Donny, you're out of your element!", movie: "The Big Lebowski", year: 1998),
    Quote(id: 342, text: "This will not stand, ya know, this aggression will not stand, man.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 343, text: "Careful, man, there's a beverage here!", movie: "The Big Lebowski", year: 1998),
    Quote(id: 344, text: "I'm finishing my coffee.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 345, text: "Smokey, this is not 'Nam. This is bowling. There are rules.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 346, text: "Mark it zero!", movie: "The Big Lebowski", year: 1998),
    Quote(id: 347, text: "Am I the only one around here who gives a shit about the rules?", movie: "The Big Lebowski", year: 1998),
    Quote(id: 348, text: "You want a toe? I can get you a toe.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 349, text: "Eight-year-olds, Dude.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 350, text: "New shit has come to light!", movie: "The Big Lebowski", year: 1998)
]
