// Scraped quotes from Wikiquote
let scrapedQuotes: [Quote] = [
    Quote(id: 700, text: "I always think everything could be a trap...which is why I'm still alive.", movie: "The Princess Bride", year: 1987),
    Quote(id: 701, text: "Man in Black Then make your choice.", movie: "The Princess Bride", year: 1987),
    Quote(id: 702, text: "Scaling the Cliffs of Insanity, Battling Rodents of Unusual Size, Facing torture in the Pit of Despair. - True love has never been a snap.", movie: "The Princess Bride", year: 1987),
    Quote(id: 703, text: "It's as real as the feelings you feel", movie: "The Princess Bride", year: 1987),
    Quote(id: 704, text: "Heroes. Giants. Villains. Miracle Men. True Love. - Not just your basic, average, everyday, ordinary, run-of-the-mill, ho-hum fairy tale.", movie: "The Princess Bride", year: 1987),
    Quote(id: 705, text: "She gets kidnapped. He gets killed. But it all ends up okay.", movie: "The Princess Bride", year: 1987),
    Quote(id: 706, text: "OH, MY GOD! HER DRESS IS ON FIRE! SHE'S ON FIRE!!!", movie: "The Princess Bride", year: 1987),
    Quote(id: 707, text: "You're setting fire to Robin on the first day?! What are you, nuts? It's not like we can replace her!", movie: "The Princess Bride", year: 1987),
    Quote(id: 708, text: "It was in one of those cinema books as one of the greatest screenplays ever written that had never been produced.", movie: "The Princess Bride", year: 1987),
    Quote(id: 709, text: "If my calculations are correct, when this baby hits 88 miles per hour, you're gonna see some serious shit.", movie: "Back to the Future", year: 1985),
    Quote(id: 710, text: "Next Saturday night, we're sending you back to the future!", movie: "Back to the Future", year: 1985),
    Quote(id: 711, text: "I'm sure that in 1985, plutonium is available in every corner drugstore, but in 1955, it's a little hard to come by.", movie: "Back to the Future", year: 1985),
    Quote(id: 712, text: "Since you're new here, I-I'm gonna cut you a break, today. So, why don't you make like a tree and get outta here?", movie: "Back to the Future", year: 1985),
    Quote(id: 713, text: "Meet Marty McFly. He's broken the time barrier. Busted his parents' first date. And, maybe, botched his chances of ever being born.", movie: "Back to the Future", year: 1985),
    Quote(id: 714, text: "17-year-old Marty McFly got home early last night. 30 years early.", movie: "Back to the Future", year: 1985),
    Quote(id: 715, text: "Marty McFly just broke the time barrier. He's only got one week to get it fixed.", movie: "Back to the Future", year: 1985),
    Quote(id: 716, text: "Marty McFly's having the time of his life. The only question is—what time is it?", movie: "Back to the Future", year: 1985),
    Quote(id: 717, text: "He was never in time for his classes... He wasn't in time for his dinner... Then one day... he wasn't in his time at all.", movie: "Back to the Future", year: 1985),
    Quote(id: 718, text: "Bumping into your parents is no big deal unless you bump into them before you were born.", movie: "Back to the Future", year: 1985),
    Quote(id: 719, text: "He's the only kid ever to get into trouble before he was born.", movie: "Back to the Future", year: 1985),
    Quote(id: 720, text: "Hello? Anybody home? Think McFly, Think!", movie: "Back to the Future", year: 1985),
    Quote(id: 721, text: "Marty McFly has just come between the most unlikely couple in high school... His parents.", movie: "Back to the Future", year: 1985),
    Quote(id: 722, text: "Marty McFly's future is catching up with him.", movie: "Back to the Future", year: 1985),
    Quote(id: 723, text: "Marty McFly took a spin in a new sports car last night. But he never got past '55. 1955.", movie: "Back to the Future", year: 1985),
    Quote(id: 724, text: "The story of a young man with a great future behind him.", movie: "Back to the Future", year: 1985),
    Quote(id: 725, text: "Marty's parents were destined to meet in 1955. Until Marty dropped in from the future.", movie: "Back to the Future", year: 1985),
    Quote(id: 726, text: "Before rock and roll , Before diet soda , Before designer jeans , running shoes and video games… One boy had a vision of what was to come — because he had just been there.", movie: "Back to the Future", year: 1985),
    Quote(id: 727, text: "Mark Ames, Going Postal: Rage, Murder and Rebellion: From Reagan's Workplaces to Clinton's Columbine and Beyond (2005), p.&nbsp;192", movie: "Back to the Future", year: 1985),
    Quote(id: 728, text: "I think the first film resonates so well with audiences because of the element of wish-fulfilment at its heart. We've all said to ourselves, \"I wish I could go back in time and change something\" or, \"If only I could do that over again.\"", movie: "Back to the Future", year: 1985),
    Quote(id: 729, text: "Chicks cannot hold their smoke, dat's what it is.", movie: "The Breakfast Club", year: 1985),
    Quote(id: 730, text: "Screws fall out all the time; the world is an imperfect place.", movie: "The Breakfast Club", year: 1985),
    Quote(id: 731, text: "Hey, how come Andrew gets to get up? If he gets up, we'll all get up…it'll be anarchy!'", movie: "The Breakfast Club", year: 1985),
    Quote(id: 732, text: "Yeah, I got a question. Does Barry Manilow know that you raid his wardrobe?", movie: "The Breakfast Club", year: 1985),
    Quote(id: 733, text: "They only met once, but it changed their lives forever.", movie: "The Breakfast Club", year: 1985),
    Quote(id: 734, text: "They were five total strangers, with nothing in common, meeting for the first time. A brain, a beauty, a jock, a rebel and a recluse. Before the day was over, they broke the rules. Bared their souls and touched each other in a way they never dreamed possible.", movie: "The Breakfast Club", year: 1985),
    Quote(id: 735, text: "Five strangers with nothing in common, except each other.", movie: "The Breakfast Club", year: 1985),
    Quote(id: 736, text: "Personally, I liked the University. They gave us money and facilities, we didn't have to produce anything! You've never been out of college! You don't know what it's like out there! I've worked in the private sector. They expect results.", movie: "Ghostbusters", year: 1984),
    Quote(id: 737, text: "Ah, If there's a steady paycheck in it, I'll believe anything you say.", movie: "Ghostbusters", year: 1984),
    Quote(id: 738, text: "Archbishop (Mike): Lenny, officially, the Church will not take any position on the religious implications of these phenomena. Personally, Lenny, I think it's a sign from God. But don't quote me on that.", movie: "Ghostbusters", year: 1984),
    Quote(id: 739, text: "Rarely has a movie this expensive provided so many quotable lines.", movie: "Ghostbusters", year: 1984),
    Quote(id: 740, text: "Catching the un-dead is their life. It's not a pretty job...especially the way they do it. But somebody has to.", movie: "Ghostbusters", year: 1984),
    Quote(id: 741, text: "They're Here To Save The World.", movie: "Ghostbusters", year: 1984),
    Quote(id: 742, text: "Coming To Save The World This Summer.", movie: "Ghostbusters", year: 1984),
    Quote(id: 743, text: "We're Ready To Believe You.", movie: "Ghostbusters", year: 1984),
    Quote(id: 744, text: "Who you going to call? Ghostbusters!", movie: "Ghostbusters", year: 1984),
    Quote(id: 745, text: "The supernatural spectacular", movie: "Ghostbusters", year: 1984),
    Quote(id: 746, text: "They ain't afraid of no ghost.", movie: "Ghostbusters", year: 1984),
    Quote(id: 747, text: "The world's most successful comedy", movie: "Ghostbusters", year: 1984),
    Quote(id: 748, text: "No spook, specter, or haunt will ever be safe again.", movie: "Ghostbusters", year: 1984),
    Quote(id: 749, text: "Nine million terrorists in the world and I gotta kill the one with feet smaller than my sister...", movie: "Die Hard", year: 1988),
    Quote(id: 750, text: "Who said we were terrorists?", movie: "Die Hard", year: 1988),
    Quote(id: 751, text: "\"...and when Alexander saw the breadth of his domain, he wept, for there were no more worlds to conquer...\" Benefits of a classical education.", movie: "Die Hard", year: 1988),
    Quote(id: 752, text: "High above the city of L.A. a team of terrorists has seized a building, taken hostages and declared war. One man has managed to escape. An off-duty cop hiding somewhere inside. He's alone, tired... and the only chance anyone has got.", movie: "Die Hard", year: 1988),
    Quote(id: 753, text: "Thirteen terrorists. One cop. The odds are against John McClane... That's just the way he likes it.", movie: "Die Hard", year: 1988),
    Quote(id: 754, text: "He's the only chance anyone has got.", movie: "Die Hard", year: 1988),
    Quote(id: 755, text: "It's Christmas Eve In L.A. And The Party Action's About To Explode... On The Fortieth Floor!", movie: "Die Hard", year: 1988),
    Quote(id: 756, text: "Suspense, Excitement, Adventure, On every level!", movie: "Die Hard", year: 1988),
    Quote(id: 757, text: "40 Stories High &mdash; with Suspense, Excitement and Adventure on every level!", movie: "Die Hard", year: 1988),
    Quote(id: 758, text: "40 Stories of Sheer Adventure", movie: "Die Hard", year: 1988),
    Quote(id: 759, text: "Come with me if you want to live.", movie: "The Terminator", year: 1984),
    Quote(id: 760, text: "* Note: bolded line is ranked #37 in AFI's 100 Years...100 Movie Quotes.", movie: "The Terminator", year: 1984),
    Quote(id: 761, text: "It came from a war-torn future to destroy the past. Its target: an ordinary woman - Sarah Connor. Her only ally: another traveler through time.", movie: "The Terminator", year: 1984),
    Quote(id: 762, text: "The machines rose from the ashes of the nuclear fire. Their war to exterminate mankind had raged for decades, but the final battle would not be fought in the future. It would be fought here, in our present. Tonight...", movie: "The Terminator", year: 1984),
    Quote(id: 763, text: "In the Year of Darkness, 2029, the rulers of this planet devised the ultimate plan. They would reshape the Future by changing the Past. The plan required something that felt no pity. No pain. No fear. Something unstoppable. They created the Terminator.", movie: "The Terminator", year: 1984),
    Quote(id: 764, text: "The thing that won't die, in the nightmare that won't end.", movie: "The Terminator", year: 1984),
    Quote(id: 765, text: "Your future is in its hands.", movie: "The Terminator", year: 1984),
    Quote(id: 766, text: "There is no fate but what we make for ourselves.", movie: "The Terminator", year: 1984),
    Quote(id: 767, text: "Now, I get invitations to everything and anything, but for some reason, I never got an invitation to the screening of The Terminator.", movie: "The Terminator", year: 1984),
    Quote(id: 768, text: "He is afraid. He is alone. He is three million light years from home.", movie: "E.T. the Extra-Terrestrial", year: 1982),
    Quote(id: 769, text: "His adventure on Earth.", movie: "E.T. the Extra-Terrestrial", year: 1982),
    Quote(id: 770, text: "The mystery. The suspense. The adventure. The call... that started it all.", movie: "E.T. the Extra-Terrestrial", year: 1982),
    Quote(id: 771, text: "The story that touched the world!", movie: "E.T. the Extra-Terrestrial", year: 1982),
    Quote(id: 772, text: "Twenty years ago, one legacy, one touch, one story that touched the world.", movie: "E.T. the Extra-Terrestrial", year: 1982),
    Quote(id: 773, text: "I wanted to thank you for bringing E.T. to the White House. We really enjoyed your movie. And there are a number of people in this room who know that everything on that screen is absolutely true.", movie: "E.T. the Extra-Terrestrial", year: 1982),
    Quote(id: 774, text: "Jules But Marsellus Wallace don't like to be fucked by anybody except Mrs. Wallace. You read the Bible, Brett?", movie: "Pulp Fiction", year: 1994),
    Quote(id: 775, text: "Girls like me don't make invitations like this to just anyone!", movie: "Pulp Fiction", year: 1994),
    Quote(id: 776, text: "You won't know the facts until you've seen the fiction", movie: "Pulp Fiction", year: 1994),
    Quote(id: 777, text: "Zed's dead, baby. Zed's dead.", movie: "Pulp Fiction", year: 1994),
    Quote(id: 778, text: "Well, sir, it's this rug I had. It really tied the room together.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 779, text: "Look, let me explain something to you. I'm not Mr. Lebowski. You're Mr. Lebowski. I'm the Dude. So that's what you call me. That, or His Dudeness, Duder or El Duderino, if you're not into the whole brevity thing.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 780, text: "This aggression will not stand, man.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 781, text: "This is a very complicated case, Maude. You know, a lotta ins, lotta outs, lotta what-have-you's. And, uh, lotta strands to keep in my head, man. Lotta strands in old Duder's head. Luckily I'm adhering to a pretty strict, uh, drug regimen to keep my mind, you know, limber.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 782, text: "Walter, I love you, but sooner or later, you're going to have to face the fact you're a goddamn moron.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 783, text: "You're not wrong Walter. You're just an asshole.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 784, text: "I'm perfectly calm, Dude.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 785, text: "Nihilists! Fuck me. I mean, say what you want about the tenets of National Socialism, Dude, at least it's an ethos.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 786, text: "Eh, fuck it, Dude. Let's go bowling.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 787, text: "Life does not start and stop at your convenience, you miserable piece of shit!", movie: "The Big Lebowski", year: 1998),
    Quote(id: 788, text: "Language problem here. Little prick stonewalling me.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 789, text: "Who am I? I'm a fucking veteran that's who I am!", movie: "The Big Lebowski", year: 1998),
    Quote(id: 790, text: "A wiser man than myself once said, \"Sometimes you eat the b'ar.… Sometimes the b'ar, well, he eats you.\"", movie: "The Big Lebowski", year: 1998),
    Quote(id: 791, text: "They figured he was a lazy, time-wasting slacker. They were right.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 792, text: "Her life was in their hands. Now her toe is in the mail.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 793, text: "Times like these call for a Big Lebowski.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 794, text: "It takes guys as simple as the Dude and Walter to make a story this complicated … and they'd really rather be bowling.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 795, text: "Alphabetized by author", movie: "The Big Lebowski", year: 1998),
    Quote(id: 796, text: "The Dude is an extreme case, but he provides an ideal which can help you to bring a little more \"Dude\" into your life, without giving up on the rat race entirely.", movie: "The Big Lebowski", year: 1998),
    Quote(id: 797, text: "Mama always said, dying was a part of life. I sure wish it wasn't.", movie: "Forrest Gump", year: 1994),
    Quote(id: 798, text: "My Mama always said you've got to put the past behind you before you can move on.", movie: "Forrest Gump", year: 1994),
    Quote(id: 799, text: "My Momma always said, \"Life is like a box of chocolates. You never know what you're gonna get.\"", movie: "Forrest Gump", year: 1994),
    Quote(id: 800, text: "Yes, drill sergeant!", movie: "Forrest Gump", year: 1994),
    Quote(id: 801, text: "Now, you listen to me. We all have a destiny. Things don't just happen, it's all part of a plan.", movie: "Forrest Gump", year: 1994),
    Quote(id: 802, text: "Recruit #1: Seat's taken.", movie: "Forrest Gump", year: 1994),
    Quote(id: 803, text: "Recruit #2: Taken.", movie: "Forrest Gump", year: 1994),
    Quote(id: 804, text: "Forrest Gump, Recruits: YES, DRILL SERGEANT!", movie: "Forrest Gump", year: 1994),
    Quote(id: 805, text: "The Matrix is arguably the ultimate cyberpunk artifact.", movie: "The Matrix", year: 1999),
    Quote(id: 806, text: "Written and directed by the Wachowski Brothers, Larry and Andy, \"The Matrix\" is the unlikely spiritual love child of dark futurist Philip K. Dick and the snap and dazzle of Hong Kong filmmaking, with digital technology serving as the helpful midwife.", movie: "The Matrix", year: 1999),
    Quote(id: 807, text: "It's a story about consciousness, a child's perception of an adult's world. The Matrix is about the birth and evolution of consciousness. It starts off crazy, then things start to make sense", movie: "The Matrix", year: 1999),
    Quote(id: 808, text: "Be Afraid of the Future.", movie: "The Matrix", year: 1999),
    Quote(id: 809, text: "Free your mind.", movie: "The Matrix", year: 1999),
    Quote(id: 810, text: "The Fight for the Future Begins.", movie: "The Matrix", year: 1999),
    Quote(id: 811, text: "Believe the unbelievable.", movie: "The Matrix", year: 1999),
    Quote(id: 812, text: "Reality is a thing of the past.", movie: "The Matrix", year: 1999),
    Quote(id: 813, text: "What is The Matrix?", movie: "The Matrix", year: 1999),
    Quote(id: 814, text: "Unfortunately, no one can be told what the Matrix is. You have to see it for yourself.", movie: "The Matrix", year: 1999),
    Quote(id: 815, text: "Welcome to the Real World.", movie: "The Matrix", year: 1999),
    Quote(id: 816, text: "There is no spoon.", movie: "The Matrix", year: 1999),
    Quote(id: 817, text: "I can only show you the door, you have to walk through it.", movie: "The Matrix", year: 1999),
    Quote(id: 818, text: "Follow the white rabbit.", movie: "The Matrix", year: 1999),
    Quote(id: 819, text: "In a world of 1s and 0s... are you a zero, or The One?", movie: "The Matrix", year: 1999),
    Quote(id: 820, text: "Future is not User Friendly.", movie: "The Matrix", year: 1999),
    Quote(id: 821, text: "Paulie might've moved slow, but it was only because Paulie didn't have to move for anybody.", movie: "Goodfellas", year: 1990),
    Quote(id: 822, text: "One day some of the kids from the neighborhood carried my mother's groceries all the way home. You know why? It was outta respect.", movie: "Goodfellas", year: 1990),
    Quote(id: 823, text: "Saturday night was for wives, but Friday night at the Copa was always for the girlfriends.", movie: "Goodfellas", year: 1990),
    Quote(id: 824, text: "For a second, I thought I was dead, but when I heard all the noise I knew they were cops. Only cops talk that way. If they had been wiseguys, I wouldn't have heard a thing. I would've been dead.", movie: "Goodfellas", year: 1990),
    Quote(id: 825, text: "I know there are women, like my best friends, who would have gotten out of there the minute their boyfriend gave them a gun to hide. But I didn't. I gotta admit the truth. It turned me on.", movie: "Goodfellas", year: 1990),
    Quote(id: 826, text: "But still I couldn't hurt him. How could I hurt him? I couldn't even bring myself to leave him. The truth was that no matter how bad I felt I was still very attracted to him. Why should I give him to someone else? Why should she win?", movie: "Goodfellas", year: 1990),
    Quote(id: 827, text: "Visitor's center", movie: "Goodfellas", year: 1990),
    Quote(id: 828, text: "Henry's Children: Daddy! Oh, we missed you! Are you out here to stay? Did you see our pictures? I did the one with the house and the rainbow.", movie: "Goodfellas", year: 1990),
    Quote(id: 829, text: "Three Decades of Life in the Mafia.", movie: "Goodfellas", year: 1990),
    Quote(id: 830, text: "\"As far back as I can remember, I've always wanted to be a gangster.\"—Henry Hill, Brooklyn, N.Y. 1955.", movie: "Goodfellas", year: 1990),
    Quote(id: 831, text: "Murderers come with smiles.", movie: "Goodfellas", year: 1990),
    Quote(id: 832, text: "Shooting people was 'No big deal'.", movie: "Goodfellas", year: 1990),
    Quote(id: 833, text: "In a world that's powered by violence, on the streets where the violent have power, a new generation carries on an old tradition.", movie: "Goodfellas", year: 1990),
    Quote(id: 834, text: "These prison walls are funny. First you hate 'em, then you get used to 'em. Enough time passes, gets so you depend on them. That's institutionalized. They send you here for life, that's exactly what they take. The part that counts, anyways.", movie: "The Shawshank Redemption", year: 1994),
    Quote(id: 835, text: "I like to think the last thing that went through his head, other than that bullet, was how the hell that Andy Dufrense ever got the best of him.", movie: "The Shawshank Redemption", year: 1994),
    Quote(id: 836, text: "If you wanna indulge in this fantasy, that's your business. Don't make it mine. This meeting is over.", movie: "The Shawshank Redemption", year: 1994),
    Quote(id: 837, text: "I want him found. NOT TOMORROW, NOT AFTER BREAKFAST! NOW!", movie: "The Shawshank Redemption", year: 1994),
    Quote(id: 838, text: "This is a conspiracy. That's what it is. One... BIG... DAMN CONSPIRACY! AND EVERYONE'S IN ON IT! Including her!", movie: "The Shawshank Redemption", year: 1994),
    Quote(id: 839, text: "His Judgement Cometh and that Right Soon.…", movie: "The Shawshank Redemption", year: 1994),
    Quote(id: 840, text: "Needlepoint in Norton's office, paraphrased from Sirach 21:5: \"A prayer out of a poor man's mouth reacheth to the ears of God, and his judgement cometh speedily.\"", movie: "The Shawshank Redemption", year: 1994),
    Quote(id: 841, text: "Life's a fragile thing, Harr. One minute you're chewin' on a burger, and the next minute you're dead meat.", movie: "Dumb and Dumber", year: 1994),
    Quote(id: 842, text: "Mary, I desperately want to make love to a schoolboy.", movie: "Dumb and Dumber", year: 1994),
    Quote(id: 843, text: "Yeah, I'm heading to Aspen myself. Maybe we could meet up and have some hot chocolate.", movie: "Dumb and Dumber", year: 1994),
    Quote(id: 844, text: "You know, Lloyd, just when I think you couldn't possibly be any dumber, you go and do something like this... and totally redeem yourself!", movie: "Dumb and Dumber", year: 1994),
    Quote(id: 845, text: "(he's about to walk away)", movie: "Dumb and Dumber", year: 1994),
    Quote(id: 846, text: "(she drives away)", movie: "Dumb and Dumber", year: 1994),
    Quote(id: 847, text: "What the one doesn't have, the other is missing.", movie: "Dumb and Dumber", year: 1994),
    Quote(id: 848, text: "For Harry and Lloyd every day is a no-brainer.", movie: "Dumb and Dumber", year: 1994),
    Quote(id: 849, text: "So, okay, you're probably going, \"Is this, like, a Noxzema commercial or what?\" But seriously, I actually have a way normal life for a teenage girl.", movie: "Clueless", year: 1995),
    Quote(id: 850, text: "Dionne and I were both named after great singers of the past who now do infomercials.", movie: "Clueless", year: 1995),
    Quote(id: 851, text: "Suddenly, a dark cloud settled over first period. I got a C in Debate?!", movie: "Clueless", year: 1995),
    Quote(id: 852, text: "Isn't my house classic? The columns date all the way back to 1972.", movie: "Clueless", year: 1995),
    Quote(id: 853, text: "Wasn't my mom a Betty? She died when I was just a baby. A fluke accident during a routine liposuction.", movie: "Clueless", year: 1995),
    Quote(id: 854, text: "Searching for a boy in high school is as useless as searching for meaning in a Pauly Shore movie.", movie: "Clueless", year: 1995),
    Quote(id: 855, text: "Anything you can do to draw attention to your mouth is good. Also, sometimes you have to show a little skin. This reminds guys of being naked, and then they think of sex.", movie: "Clueless", year: 1995),
    Quote(id: 856, text: "Sex. Clothes. Popularity. Is there a problem here?", movie: "Clueless", year: 1995),
    Quote(id: 857, text: "Sex. Clothes. Popularity. Whatever.", movie: "Clueless", year: 1995),
    Quote(id: 858, text: "Would you fuck me? I'd fuck me. I'd fuck me hard. I'd fuck me so hard...", movie: "The Silence of the Lambs", year: 1991),
    Quote(id: 859, text: "*Note: bolded sentence ranked #21 in the American Film Institute's list of the top 100 movie quotations in American cinema.", movie: "The Silence of the Lambs", year: 1991),
    Quote(id: 860, text: "To enter the mind of a killer, she must challenge the mind of a madman.", movie: "The Silence of the Lambs", year: 1991),
    Quote(id: 861, text: "Prepare yourself for the most exciting, mesmerising and terrifying two hours of your life!", movie: "The Silence of the Lambs", year: 1991),
    Quote(id: 862, text: "When the Fox hears the Rabbit scream he comes a-runnin', but not to help.", movie: "The Silence of the Lambs", year: 1991),
    Quote(id: 863, text: "May The Silence Be Broken!!", movie: "The Silence of the Lambs", year: 1991),
    Quote(id: 864, text: "Dr. Hannibal Lecter. Brilliant. Cunning. Psychotic. In his mind lies the clue to a ruthless killer. &ndash; Clarice Starling, FBI. Brilliant. Vulnerable. Alone. She must trust him to stop the killer.", movie: "The Silence of the Lambs", year: 1991),
    Quote(id: 865, text: "Gloria E. Anzaldúa interview in Backtalk: women writers speak out by Donna Marie Perry (1993)", movie: "The Silence of the Lambs", year: 1991),
    Quote(id: 866, text: "I thought that in that movie The Elephant Man, that he was the ultimate good doctor, just the greatest doctor of all. So my thinking was, what happens if the greatest doctor of all goes wrong?", movie: "The Silence of the Lambs", year: 1991),
    Quote(id: 867, text: "It’s about one young woman trying desperately to save the life of another young woman. And in order to do that, she’s faced with the overwhelming obstacle of all these men", movie: "The Silence of the Lambs", year: 1991),
]
